# Generated by Django 5.1.1 on 2024-11-13 19:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import gestion_pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_aprobaciones', '0001_initial'),
        ('gestion_clientes', '0024_rename_comercialmargin_commercialmargin_and_more'),
        ('gestion_plan_importacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('grupo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Genérico de Producto',
                'verbose_name_plural': 'Genéricos de Producto',
            },
        ),
        migrations.CreateModel(
            name='UnidadCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Unidad de Compra',
                'verbose_name_plural': 'Unidades de Compra',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_711', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El formato debe ser números seguidos de /OC', regex='^[0-9]+/OC$')])),
                ('fecha_entrada_tecnotex', models.DateTimeField(default=django.utils.timezone.now, validators=[gestion_pedidos.models.validate_date_range_three_days])),
                ('financiamiento', models.CharField(max_length=100)),
                ('presentador', models.CharField(max_length=200)),
                ('tipo_pedido', models.CharField(max_length=100)),
                ('fecha_presentado', models.DateTimeField(default=django.utils.timezone.now, validators=[gestion_pedidos.models.validate_date_range_three_days])),
                ('aprobacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aprobaciones.aprobacion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.client')),
                ('codigos_aprobacion', models.ManyToManyField(related_name='pedidos_relacionados', to='gestion_aprobaciones.codigoaprobacion')),
                ('generico_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.genericoproducto')),
                ('plan_importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_plan_importacion.planimportacion')),
                ('unidad_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.unidadcompra')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
