# Generated by Django 5.1.1 on 2024-11-15 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aprobaciones', '0001_initial'),
        ('gestion_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.IntegerField()),
                ('descripcion_producto', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('especificaciones_tecnicas', models.TextField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('denominacion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aprobaciones.aprobacion')),
                ('codigo_aprobacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aprobaciones.codigoaprobacion')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='gestion_pedidos.pedido')),
                ('productos', models.ManyToManyField(to='gestion_pedidos.producto')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.unidadmedida'),
        ),
    ]
