# Generated by Django 5.1.1 on 2024-11-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aprobaciones', '0001_initial'),
        ('gestion_pedidos', '0002_producto_unidadmedida_posicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='aprobacion',
        ),
        migrations.AddField(
            model_name='pedido',
            name='aprobaciones',
            field=models.ManyToManyField(related_name='pedidos', to='gestion_aprobaciones.aprobacion', verbose_name='Aprobaciones'),
        ),
    ]
