# Generated by Django 5.1.1 on 2024-11-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0004_alter_pedido_financiamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='grupo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
