# Generated by Django 5.1.1 on 2024-11-24 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0005_pedido_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='generico_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.genericoproducto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='presentador',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='unidad_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.unidadcompra'),
        ),
    ]
