# Generated by Django 5.1.1 on 2024-09-13 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="contrato",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gestion_clientes.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="correo_Cliente",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
