# Generated by Django 5.1.1 on 2024-09-13 22:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_clientes",
            "0002_alter_cliente_contrato_alter_cliente_correo_cliente",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="margencomercial",
            old_name="cantidad",
            new_name="margen_comercial",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="polo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="gestion_clientes.polo"
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="fecha_firma",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="representante",
            name="correo_representante",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="representante",
            name="telefono_representante",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono debe tener el formato +53 XXXX-XXXX o +53 XXXXXXXX",
                        regex="^\\+53\\s\\d{4}\\-\\d{4}$|^\\+53\\s\\d{8}$",
                    )
                ],
            ),
        ),
    ]
