# Generated by Django 5.1.1 on 2024-09-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_clientes",
            "0003_rename_cantidad_margencomercial_margen_comercial_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="polo",
        ),
    ]
