# Generated by Django 5.1.1 on 2024-09-13 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0004_remove_cliente_polo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="polo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="gestion_clientes.polo",
            ),
        ),
    ]
