# Generated by Django 5.1.1 on 2024-09-13 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0006_alter_cliente_polo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="numero_contrato",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El numero de contrato debe tener el formato TX-XXXXX",
                        regex="^TX-\\d{5}",
                    )
                ],
            ),
        ),
    ]
