# Generated by Django 5.1.1 on 2024-09-13 22:53

import gestion_clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0008_alter_contrato_numero_contrato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="fecha_firma",
            field=models.DateField(blank=True, null=True),
        ),
    ]
