# Generated by Django 5.1.1 on 2024-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0009_alter_contrato_fecha_firma"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="estado_cliente",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contrato",
            name="estado_contrato",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="margencomercial",
            name="estado_margen_comercial",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="polo",
            name="estado_polo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="representante",
            name="estado_representante",
            field=models.BooleanField(default=True),
        ),
    ]
