# Generated by Django 5.1.1 on 2024-09-18 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_clientes",
            "0010_cliente_estado_cliente_contrato_estado_contrato_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="ubi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gestion_clientes.cliente",
            ),
        ),
    ]
