# Generated by Django 5.1.1 on 2024-09-18 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0011_cliente_ubi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="ubi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion_clientes.cliente",
            ),
        ),
    ]
