# Generated by Django 5.1.1 on 2024-09-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0012_alter_cliente_ubi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente",
            old_name="correo_Cliente",
            new_name="correo_cliente",
        ),
    ]
