# Generated by Django 5.1.1 on 2024-09-28 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0014_alter_cliente_codigo_reeup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="fax",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono debe tener el formato +53 XXXXXXXX",
                        regex="^\\+53\\s\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero_contrato",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El numero de contrato debe tener el formato TX-ddddd",
                        regex="^TX-\\d{5}",
                    )
                ],
            ),
        ),
    ]
