# Generated by Django 5.1.1 on 2024-09-28 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0015_alter_cliente_fax_alter_contrato_numero_contrato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="codigo",
            field=models.CharField(
                max_length=25,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El código del cliente debe tener 5 dígitos",
                        regex="^\\d{5}",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="codigo_nip",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El código NIP debe tener 9 dígitos", regex="^\\d{9}"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero_contrato",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número de contrato debe tener el formato TX-ddddd",
                        regex="^TX-\\d{5}",
                    )
                ],
            ),
        ),
    ]
