# Generated by Django 5.1.1 on 2024-09-29 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_clientes",
            "0016_alter_cliente_codigo_alter_cliente_codigo_nip_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="es_aei",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="representante",
            name="correo_representante",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="representante",
            name="telefono_representante",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono debe tener el formato +53 XXXXXXXX",
                        regex="^\\+53\\s\\d{8}$",
                    )
                ],
            ),
        ),
    ]
