# Generated by Django 5.1.1 on 2024-09-30 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0017_alter_cliente_es_aei_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="margencomercial",
            name="margen_comercial",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
