# Generated by Django 5.1.1 on 2024-10-01 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_clientes", "0019_alter_margencomercial_margen_comercial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representante",
            name="telefono_representante",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono debe tener el formato +53 XXXXXXXX",
                        regex="^\\+53\\s\\d{8}$",
                    )
                ],
            ),
        ),
    ]
