# Generated by Django 5.1.1 on 2024-10-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_clientes",
            "0021_alter_cliente_codigo_alter_cliente_codigo_reeup_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="entre_calle",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="pais",
            field=models.CharField(
                blank=True, default="Cuba", max_length=50, null=True
            ),
        ),
    ]
