# Generated by Django 5.1.1 on 2024-11-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aprobaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprobacion',
            options={'verbose_name': 'Aprobacion', 'verbose_name_plural': 'Aprobaciones'},
        ),
        migrations.AlterModelOptions(
            name='casafinanciera',
            options={'verbose_name': 'Casa Financiera', 'verbose_name_plural': 'Casas Financieras'},
        ),
        migrations.AlterModelOptions(
            name='codigoaprobacion',
            options={'verbose_name': 'Codigo de Aprobacion', 'verbose_name_plural': 'Codigos de Aprobaciones'},
        ),
        migrations.AlterModelOptions(
            name='financiero',
            options={'verbose_name': 'Financiero', 'verbose_name_plural': 'Financieros'},
        ),
        migrations.AlterModelOptions(
            name='objeto',
            options={'verbose_name': 'Objeto', 'verbose_name_plural': 'Objetos'},
        ),
        migrations.AlterModelOptions(
            name='tipofactura',
            options={'verbose_name': 'Tipo de Factura', 'verbose_name_plural': 'Tipos de Facturas'},
        ),
    ]
