# Generated by Django 5.1.1 on 2024-11-13 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0024_rename_comercialmargin_commercialmargin_and_more'),
        ('gestion_plan_importacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
            },
        ),
        migrations.AlterModelOptions(
            name='extraplan',
            options={'verbose_name': 'Extraplan', 'verbose_name_plural': 'Extraplanes'},
        ),
        migrations.RenameField(
            model_name='extraplan',
            old_name='importe',
            new_name='importe_extraplan',
        ),
        migrations.RenameField(
            model_name='planimportacion',
            old_name='importe_actual',
            new_name='importe_pi',
        ),
        migrations.RemoveField(
            model_name='extraplan',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='planimportacion',
            name='estadistica',
        ),
        migrations.RemoveField(
            model_name='planimportacion',
            name='fecha_entrada_tecnotex',
        ),
        migrations.RemoveField(
            model_name='planimportacion',
            name='importe_inicial',
        ),
        migrations.RemoveField(
            model_name='planimportacion',
            name='objeto',
        ),
        migrations.AddField(
            model_name='extraplan',
            name='codigo_extraplan',
            field=models.CharField(editable=False, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='extraplan',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='planimportacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.client', unique_for_year='anio_pi'),
        ),
        migrations.AlterField(
            model_name='planimportacion',
            name='codigo_pi',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='planimportacion',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DesglosePI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_por_objeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mediano_plazo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largo_plazo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desglose_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('plan_importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desgloses', to='gestion_plan_importacion.planimportacion')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_plan_importacion.objeto')),
            ],
        ),
        migrations.CreateModel(
            name='DesgloseExtraplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_por_objeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mediano_plazo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largo_plazo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desglose_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('extraplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desgloses', to='gestion_plan_importacion.extraplan')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_plan_importacion.objeto')),
            ],
        ),
    ]
