# Generated by Django 5.1.1 on 2024-11-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_plan_importacion', '0002_objeto_alter_extraplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='extraplanes',
            field=models.ManyToManyField(related_name='objetos', through='gestion_plan_importacion.DesgloseExtraplan', to='gestion_plan_importacion.extraplan'),
        ),
        migrations.AddField(
            model_name='planimportacion',
            name='objetos',
            field=models.ManyToManyField(related_name='planes_importacion', through='gestion_plan_importacion.DesglosePI', to='gestion_plan_importacion.objeto'),
        ),
    ]
