# Generated by Django 5.1.1 on 2024-11-16 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0024_rename_comercialmargin_commercialmargin_and_more'),
        ('gestion_plan_importacion', '0002_objeto_alter_extraplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planimportacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.client'),
        ),
        migrations.AlterUniqueTogether(
            name='planimportacion',
            unique_together={('cliente', 'anio_pi')},
        ),
    ]
